# Generated by Django 5.0.2 on 2025-06-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('SHORT', 'Short'), ('LONG', 'Long')], default='SHORT', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('GENERATING', 'Üretimde'), ('ERROR', 'Hata'), ('COMPLETED', 'Tamamlandı')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voices/')),
                ('background_music', models.FileField(blank=True, null=True, upload_to='music/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='final_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='panels.panel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video_images/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='videos.video')),
            ],
        ),
    ]
