# Generated by Django 5.2.3 on 2025-06-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='generated_text',
        ),
        migrations.CreateModel(
            name='VideoAIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('script', models.TextField()),
                ('hashtags', models.JSONField()),
                ('description', models.CharField(max_length=100)),
                ('thumbnail_prompt', models.TextField()),
                ('content_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content', to='videos.video')),
            ],
        ),
    ]
