# Generated by Django 5.2.3 on 2025-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_generated_text_videoaicontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaicontent',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videoaicontent',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
