# Generated by Django 5.0.2 on 2025-06-10 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('YOUTUBE_SHORTS', 'YouTube Shorts'), ('YOUTUBE_LONG', 'YouTube Long'), ('INSTAGRAM_REELS', 'Instagram Reels'), ('TIKTOK', 'TikTok')], max_length=20)),
                ('language', models.CharField(default='tr', max_length=10)),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('ad_opacity', models.FloatField(default=1.0)),
                ('ad_position', models.CharField(choices=[('TOP_LEFT', 'Top Left'), ('TOP_RIGHT', 'Top Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('BOTTOM_RIGHT', 'Bottom Right'), ('CENTER', 'Center')], default='BOTTOM_RIGHT', max_length=20)),
                ('outro_text', models.CharField(blank=True, max_length=255, null=True)),
                ('outro_video', models.FileField(blank=True, null=True, upload_to='outros/')),
                ('default_tts_voice', models.CharField(blank=True, max_length=100, null=True)),
                ('add_subtitles', models.BooleanField(default=True)),
                ('resolution_width', models.IntegerField(default=1080)),
                ('resolution_height', models.IntegerField(default=1920)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
